# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
# The name of the module we are configuring is "character"
# The "success_symbol" segment is being set to "âœ" with the color "bold green"
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red) "

# # Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Battery
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

# dart
[dart]
symbol = "ğŸ¯"
style = "bold blue"
format = "via [$symbol $version]($style) "

# golang
[golang]
symbol = "ğŸ¹"
style = "bold cyan"
format = "via [$symbol $version]($style)"

# java
[java]
symbol = "â˜•"
style = "red dimmed"
format = "via [$symbol $version]($style)"

# nodejs
[nodejs]
symbol = "â¬¢"
style = "bold green"
format = "via [$symbol $version]($style)"

# python
[python]
symbol = "ğŸ"
style = "yellow bold"
format = "via [$symbol $version]($style)"

# rust
[rust]
symbol = "ğŸ¦€"
style = "bold red"
format = "via [$symbol $version]($style)"


